USE [master]
GO
/****** Object:  Database [SimpleCMS]    Script Date: 5/8/2015 7:38:25 ðì ******/
CREATE DATABASE [SimpleCMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimpleCMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleCMS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SimpleCMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleCMS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SimpleCMS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleCMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SimpleCMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SimpleCMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SimpleCMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SimpleCMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SimpleCMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [SimpleCMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SimpleCMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SimpleCMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SimpleCMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SimpleCMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SimpleCMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SimpleCMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SimpleCMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SimpleCMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SimpleCMS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SimpleCMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SimpleCMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SimpleCMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SimpleCMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SimpleCMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SimpleCMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SimpleCMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SimpleCMS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SimpleCMS] SET  MULTI_USER 
GO
ALTER DATABASE [SimpleCMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SimpleCMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SimpleCMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SimpleCMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SimpleCMS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SimpleCMS]
GO
/****** Object:  Table [dbo].[Posts]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Posts](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](150) NOT NULL,
	[Content] [text] NOT NULL,
	[DateCreated] [datetime] NOT NULL CONSTRAINT [DF_Posts_DateCreated]  DEFAULT (getdate()),
	[DatePublished] [datetime] NOT NULL CONSTRAINT [DF_Posts_DatePublished]  DEFAULT (getdate()),
	[AuthorId] [int] NOT NULL,
	[Slug] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Posts] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PostsTagsMap]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PostsTagsMap](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[PostId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_PostsTagsMap] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Roles]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Tags]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tags](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](25) NOT NULL,
	[UrlFriendlyName] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UsersRolesMap]    Script Date: 5/8/2015 7:38:25 ðì ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsersRolesMap](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_UsersRolesMap] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [SimpleCMS] SET  READ_WRITE 
GO
